#!/bin/bash
# Uninstall Script for Salesforce Skill
#
# Removes the Salesforce skill from Claude Code.
#
# Usage:
#   ./uninstall.sh [--force]
#
# Options:
#   --force    Skip confirmation prompt

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SKILL_NAME="salesforce-dev"
INSTALL_DIR="${HOME}/.claude/skills/${SKILL_NAME}"
FORCE=false

# Parse arguments
for arg in "$@"; do
    case $arg in
        --force)
            FORCE=true
            ;;
        --help)
            echo "Usage: $0 [--force]"
            echo ""
            echo "Removes the Salesforce skill from Claude Code."
            echo ""
            echo "Options:"
            echo "  --force    Skip confirmation prompt"
            echo "  --help     Show this help message"
            exit 0
            ;;
    esac
done

print_header() {
    echo -e "${BLUE}===================================================${NC}"
    echo -e "${BLUE}  Salesforce Skill Uninstaller${NC}"
    echo -e "${BLUE}===================================================${NC}"
    echo ""
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

main() {
    print_header

    # Check if installed
    if [ ! -d "${INSTALL_DIR}" ]; then
        echo -e "${YELLOW}Skill not found at: ${INSTALL_DIR}${NC}"
        echo ""
        echo "The skill may not be installed, or it may be in a different location."
        exit 1
    fi

    echo "This will remove the Salesforce skill from:"
    echo "  ${INSTALL_DIR}"
    echo ""
    echo "The following will be removed:"
    echo "  - All scripts (${INSTALL_DIR}/scripts/)"
    echo "  - All reference guides (${INSTALL_DIR}/references/)"
    echo "  - All templates (${INSTALL_DIR}/assets/)"
    echo "  - All documentation"
    echo ""

    print_warning "This will NOT remove:"
    echo "  - Salesforce CLI (sf)"
    echo "  - Python or other system dependencies"
    echo "  - Any Salesforce orgs or data"
    echo "  - Reports generated by the skill (.claude/reports/)"
    echo ""

    if [ "$FORCE" = false ]; then
        read -p "Are you sure you want to uninstall? (y/N): " -n 1 -r
        echo ""

        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            echo "Uninstall cancelled."
            exit 0
        fi
    fi

    echo ""
    echo "Uninstalling..."
    echo ""

    # Remove installation directory
    rm -rf "${INSTALL_DIR}"
    print_success "Removed ${INSTALL_DIR}"

    # Remove PATH additions from shell profiles
    echo ""
    echo "Checking for PATH modifications..."

    for rc in "${HOME}/.bashrc" "${HOME}/.zshrc"; do
        if [ -f "$rc" ]; then
            if grep -q "# Salesforce Skill" "$rc"; then
                # Create backup
                cp "$rc" "${rc}.backup-$(date +%Y%m%d-%H%M%S)"

                # Remove PATH additions
                sed -i.bak '/# Salesforce Skill/,+1d' "$rc"
                rm -f "${rc}.bak"

                print_success "Removed PATH from $(basename "$rc")"
                echo "  └─ Backup created: ${rc}.backup-*"
            fi
        fi
    done

    echo ""
    echo -e "${GREEN}===================================================${NC}"
    echo -e "${GREEN}  Uninstall Complete${NC}"
    echo -e "${GREEN}===================================================${NC}"
    echo ""
    echo "The Salesforce skill has been removed."
    echo ""
    echo "Optional cleanup:"
    echo "  - Remove generated reports: rm -rf ~/.claude/reports/"
    echo "  - Remove SFDMU plugin: sf plugins uninstall sfdmu"
    echo ""
    echo "To reinstall:"
    echo "  ./install.sh"
    echo ""
}

main "$@"
